const messages = require("../autogenerated/grakn_pb");

function GrpcIterator(iteratorId, communicator) {
  this.nextRequest = _buildNextRequest(iteratorId);
  this.communicator = communicator;
}

GrpcIterator.prototype.nextResult = async function() {
  return await this.communicator.send(this.nextRequest).then(_handleResponse);
};

function _handleResponse(response) {
  if (response.hasDone()) return null;
  if (response.hasQueryresult()) return response.getQueryresult();
  throw "Unexpected response from server.";
}

function _buildNextRequest(iteratorId) {
  const nr = new messages.Next();
  nr.setIteratorid(iteratorId);
  const tr = new messages.TxRequest();
  tr.setNext(nr);
  return tr;
}
