/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ai.grakn.rpc.generated.IteratorId', null, global);
goog.exportSymbol('proto.ai.grakn.rpc.generated.Next', null, global);
goog.exportSymbol('proto.ai.grakn.rpc.generated.Stop', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.grakn.rpc.generated.Next = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.grakn.rpc.generated.Next, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.grakn.rpc.generated.Next.displayName = 'proto.ai.grakn.rpc.generated.Next';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.grakn.rpc.generated.Next.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.grakn.rpc.generated.Next.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.grakn.rpc.generated.Next} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.grakn.rpc.generated.Next.toObject = function(includeInstance, msg) {
  var f, obj = {
    iteratorid: (f = msg.getIteratorid()) && proto.ai.grakn.rpc.generated.IteratorId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.grakn.rpc.generated.Next}
 */
proto.ai.grakn.rpc.generated.Next.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.grakn.rpc.generated.Next;
  return proto.ai.grakn.rpc.generated.Next.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.grakn.rpc.generated.Next} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.grakn.rpc.generated.Next}
 */
proto.ai.grakn.rpc.generated.Next.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.grakn.rpc.generated.IteratorId;
      reader.readMessage(value,proto.ai.grakn.rpc.generated.IteratorId.deserializeBinaryFromReader);
      msg.setIteratorid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.grakn.rpc.generated.Next.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.grakn.rpc.generated.Next.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.grakn.rpc.generated.Next} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.grakn.rpc.generated.Next.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIteratorid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.grakn.rpc.generated.IteratorId.serializeBinaryToWriter
    );
  }
};


/**
 * optional IteratorId iteratorId = 1;
 * @return {?proto.ai.grakn.rpc.generated.IteratorId}
 */
proto.ai.grakn.rpc.generated.Next.prototype.getIteratorid = function() {
  return /** @type{?proto.ai.grakn.rpc.generated.IteratorId} */ (
    jspb.Message.getWrapperField(this, proto.ai.grakn.rpc.generated.IteratorId, 1));
};


/** @param {?proto.ai.grakn.rpc.generated.IteratorId|undefined} value */
proto.ai.grakn.rpc.generated.Next.prototype.setIteratorid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.grakn.rpc.generated.Next.prototype.clearIteratorid = function() {
  this.setIteratorid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.grakn.rpc.generated.Next.prototype.hasIteratorid = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.grakn.rpc.generated.Stop = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.grakn.rpc.generated.Stop, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.grakn.rpc.generated.Stop.displayName = 'proto.ai.grakn.rpc.generated.Stop';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.grakn.rpc.generated.Stop.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.grakn.rpc.generated.Stop.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.grakn.rpc.generated.Stop} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.grakn.rpc.generated.Stop.toObject = function(includeInstance, msg) {
  var f, obj = {
    iteratorid: (f = msg.getIteratorid()) && proto.ai.grakn.rpc.generated.IteratorId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.grakn.rpc.generated.Stop}
 */
proto.ai.grakn.rpc.generated.Stop.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.grakn.rpc.generated.Stop;
  return proto.ai.grakn.rpc.generated.Stop.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.grakn.rpc.generated.Stop} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.grakn.rpc.generated.Stop}
 */
proto.ai.grakn.rpc.generated.Stop.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai.grakn.rpc.generated.IteratorId;
      reader.readMessage(value,proto.ai.grakn.rpc.generated.IteratorId.deserializeBinaryFromReader);
      msg.setIteratorid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.grakn.rpc.generated.Stop.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.grakn.rpc.generated.Stop.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.grakn.rpc.generated.Stop} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.grakn.rpc.generated.Stop.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIteratorid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai.grakn.rpc.generated.IteratorId.serializeBinaryToWriter
    );
  }
};


/**
 * optional IteratorId iteratorId = 1;
 * @return {?proto.ai.grakn.rpc.generated.IteratorId}
 */
proto.ai.grakn.rpc.generated.Stop.prototype.getIteratorid = function() {
  return /** @type{?proto.ai.grakn.rpc.generated.IteratorId} */ (
    jspb.Message.getWrapperField(this, proto.ai.grakn.rpc.generated.IteratorId, 1));
};


/** @param {?proto.ai.grakn.rpc.generated.IteratorId|undefined} value */
proto.ai.grakn.rpc.generated.Stop.prototype.setIteratorid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.ai.grakn.rpc.generated.Stop.prototype.clearIteratorid = function() {
  this.setIteratorid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ai.grakn.rpc.generated.Stop.prototype.hasIteratorid = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.grakn.rpc.generated.IteratorId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.grakn.rpc.generated.IteratorId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ai.grakn.rpc.generated.IteratorId.displayName = 'proto.ai.grakn.rpc.generated.IteratorId';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.grakn.rpc.generated.IteratorId.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.grakn.rpc.generated.IteratorId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.grakn.rpc.generated.IteratorId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.grakn.rpc.generated.IteratorId.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.grakn.rpc.generated.IteratorId}
 */
proto.ai.grakn.rpc.generated.IteratorId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.grakn.rpc.generated.IteratorId;
  return proto.ai.grakn.rpc.generated.IteratorId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.grakn.rpc.generated.IteratorId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.grakn.rpc.generated.IteratorId}
 */
proto.ai.grakn.rpc.generated.IteratorId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.grakn.rpc.generated.IteratorId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.grakn.rpc.generated.IteratorId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.grakn.rpc.generated.IteratorId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.grakn.rpc.generated.IteratorId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.ai.grakn.rpc.generated.IteratorId.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.ai.grakn.rpc.generated.IteratorId.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.ai.grakn.rpc.generated);
