const messages = require("../autogenerated/grakn_pb");
const conceptMessages = require("../autogenerated/concept_pb");

function Concept(id, stream) {
  this.conceptId = id;
  this.stream = stream;
}

Concept.prototype.delete = function() {
  const TxRequest = new messages.TxRequest();
  const runConceptMethodRequest = new messages.RunConceptMethod();
  const conceptMethod = new conceptMessages.ConceptMethod();
  const unitDelete = new conceptMessages.Unit();
  conceptMethod.setDelete(unitDelete);
  runConceptMethodRequest.setId(this.conceptId);
  runConceptMethodRequest.setConceptmethod(conceptMethod);
  // runConceptMethodRequest.set
  // this.stream
};

module.exports = Concept;
