const messages = require("../../../autogenerated/grakn_pb");

function GrpcIteratorFactory(communicator) {
  this.communicator = communicator;
}

GrpcIteratorFactory.prototype.createQueryIterator = function (iteratorId) {
  return new GrpcQueryIterator(this.communicator, buildNextRequest(iteratorId));
};
GrpcIteratorFactory.prototype.createConceptIterator = function (iteratorId) {
  return new GrpcConceptIterator(this.communicator, buildNextRequest(iteratorId));
};
GrpcIteratorFactory.prototype.createRolePlayerIterator = function (iteratorId) {
  return new GrpcRolePlayerIterator(this.communicator, buildNextRequest(iteratorId));
};

// -- Query Iterator -- // 

function GrpcQueryIterator(communicator, nextRequest) {
  this.nextRequest = nextRequest;
  this.communicator = communicator;
};

GrpcQueryIterator.prototype.nextResult = async function () {
  return await this.communicator
    .send(this.nextRequest)
    .then(handleQueryResponse)
    .catch(e => { throw e; });
};

function handleQueryResponse(response) {
  if (response.hasDone()) return null;
  if (response.hasQueryresult()) return response.getQueryresult();
  throw "Unexpected response from server.";
}

// -- Concept Iterator -- //

function GrpcConceptIterator(communicator, nextRequest) {
  this.nextRequest = nextRequest;
  this.communicator = communicator;
}

GrpcConceptIterator.prototype.nextResult = async function () {
  return await this.communicator
    .send(this.nextRequest)
    .then(_handleConceptResponse)
    .catch(e => { throw e; });
};

function _handleConceptResponse(response) {
  if (response.hasDone()) return null;
  if (response.hasConcept()) return response.getConcept();
  throw "Unexpected response from server.";
}

// -- RolePlayer Iterator -- //

function GrpcRolePlayerIterator(communicator, nextRequest) {
  this.nextRequest = nextRequest;
  this.communicator = communicator;
}

GrpcRolePlayerIterator.prototype.nextResult = async function () {
  return await this.communicator
    .send(this.nextRequest)
    .then(_handleRolePlayerResponse)
    .catch(e => { throw e; });
};

function _handleRolePlayerResponse(response) {
  if (response.hasDone()) return null;
  if (response.hasRoleplayer()) return response.getRoleplayer();
  throw "Unexpected response from server.";
}

// - Shared helper - //

function buildNextRequest(iteratorId) {
  const nr = new messages.Next();
  nr.setIteratorid(iteratorId);
  const tr = new messages.TxRequest();
  tr.setNext(nr);
  return tr;
}

module.exports = GrpcIteratorFactory;
