const messages = require("./autogenerated/grakn_pb");
const GrpcIterator = require("./util/GrpcIterator");
const TxRequestBuilder = require("./util/TxRequestBuilder");
const GrpcCommunicator = require("./util/GrpcCommunicator");
const ConceptFactory = require("./ConceptFactory");


/**
 * This module executes the methods provided by the gRPC Tx service defined
 * inside grakn.proto and returns responses in JS data types.
 * It has 2 collaborators:
 *  - a communicator which handles gRPC requests/responses over a duplex Stream
 *  - a factory to build {Concept} objects from gRPC responses 
 */

function GraknGrpcService(txStream) {
    this.communicator = new GrpcCommunicator(txStream);
    this.conceptFactory = new ConceptFactory(this);
}

GraknGrpcService.prototype.close = function () {
    return this.communicator.end();
}

// Concept

GraknGrpcService.prototype.deleteConcept = function (id) {
    const deleteTxRequest = TxRequestBuilder.deleteConcept(id);
    return this.communicator.send(deleteTxRequest)
        .catch(e => { throw e; });
};

// Schema concept
GraknGrpcService.prototype.getLabel = function (id) {
    const getLabelTxRequest = TxRequestBuilder.getLabel(id);
    return this.communicator
        .send(getLabelTxRequest)
        .then(resp => resp.getConceptresponse().getLabel().getValue()
        ).catch(e => { throw e; });
}

GraknGrpcService.prototype.setLabel = function (id, label) {
    const setLabelTxRequest = TxRequestBuilder.setLabel(id, label);
    return this.communicator.send(setLabelTxRequest)
        .catch(e => { throw e; });
};

GraknGrpcService.prototype.isImplicit = function (id) {
    const isImplicitTxRequest = TxRequestBuilder.isImplicit(id);
    return this.communicator
        .send(isImplicitTxRequest)
        .then(resp => resp.getConceptresponse().getBool())
        .catch(e => { throw e; });
}

GraknGrpcService.prototype.getSubConcepts = function (id) {
    const getSubConceptsTxRequest = TxRequestBuilder.getSubConcepts(id);
    return this.communicator.send(getSubConceptsTxRequest)
        .then(grpcConceptResponse => _consumeConceptIterator(grpcConceptResponse, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getSuperConcepts = function (id) {
    const getSuperConceptsTxRequest = TxRequestBuilder.getSuperConcepts(id);
    return this.communicator.send(getSuperConceptsTxRequest)
        .then(grpcConceptResponse => _consumeConceptIterator(grpcConceptResponse, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getDirectSuperConcept = function (id) {
    const txRequest = TxRequestBuilder.getDirectSuperConcept(id);
    return this.communicator.send(txRequest)
        .then(grpcConceptResponse => {
            const optionalConcept = grpcConceptResponse.getConceptresponse().getOptionalconcept();
            if (optionalConcept.hasPresent()) {
                const concept = optionalConcept.getPresent();
                return this.conceptFactory.createConcept(concept);
            } else {
                return null;
            }
        })
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setDirectSuperConcept = function (id, superConcept) {
    const txRequest = TxRequestBuilder.setDirectSuperConcept(id, superConcept);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};

// Rule 

GraknGrpcService.prototype.getWhen = function (id) { };
GraknGrpcService.prototype.getThen = function (id) { };

// Role

GraknGrpcService.prototype.getRelationshipTypesThatRelateRole = function (id) {
    const txRequest = TxRequestBuilder.getRelationshipTypesThatRelateRole(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
}
GraknGrpcService.prototype.getTypesThatPlayRole = function (id) {
    const txRequest = TxRequestBuilder.getTypesThatPlayRole(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
}

// Type

GraknGrpcService.prototype.getInstances = function (id) {
    const txRequest = TxRequestBuilder.getInstances(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getAttributeTypes = function (id) {
    const txRequest = TxRequestBuilder.getAttributeTypes(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setAttributeType = function (id, type) {
    const txRequest = TxRequestBuilder.setAttributeType(id, type);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.unsetAttributeType = function (id, type) {
    const txRequest = TxRequestBuilder.unsetAttributeType(id, type);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getKeyTypes = function (id) {
    const txRequest = TxRequestBuilder.getKeyTypes(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setKeyType = function (id, keyType) {
    const txRequest = TxRequestBuilder.setKeyType(id, keyType);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.unsetKeyType = function (id, keyType) {
    const txRequest = TxRequestBuilder.unsetKeyType(id, keyType);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.isAbstract = function (id) {
    const txRequest = TxRequestBuilder.isAbstract(id);
    return this.communicator.send(txRequest)
        .then(resp => resp.getConceptresponse().getBool())
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setAbstract = function (id, bool) {
    const txRequest = TxRequestBuilder.setAbstract(id, bool);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getRolesPlayedByType = function (id) {
    const txRequest = TxRequestBuilder.getRolesPlayedByType(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setRolePlayedByType = function (id, role) {
    const txRequest = TxRequestBuilder.setRolePlayedByType(id, role);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.unsetRolePlayedByType = function (id, role) {
    const txRequest = TxRequestBuilder.unsetRolePlayedByType(id, role);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};

// Entity type

GraknGrpcService.prototype.addEntity = function (id) {
    const txRequest = TxRequestBuilder.addEntity(id);
    return this.communicator.send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConceptresponse().getConcept()))
        .catch(e => { throw e; });
};

// Relationship Type
GraknGrpcService.prototype.addRelationship = function (id) {
    const txRequest = TxRequestBuilder.addRelationship(id);
    return this.communicator.send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConceptresponse().getConcept()))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getRelatedRoles = function (id) {
    const txRequest = TxRequestBuilder.getRelatedRoles(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
}

GraknGrpcService.prototype.setRelatedRole = function (id, role) {
    const txRequest = TxRequestBuilder.setRelatedRole(id, role);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.unsetRelatedRole = function (id, role) {
    const txRequest = TxRequestBuilder.unsetRelatedRole(id, role);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};



// Attribute type
GraknGrpcService.prototype.putAttribute = async function (id, value) {
    const dataTypeTxRequest = TxRequestBuilder.getDataTypeOfType(id);
    const resp = await this.communicator.send(dataTypeTxRequest);
    const dataType = resp.getConceptresponse().getOptionaldatatype().getPresent();
    const txRequest = TxRequestBuilder.putAttribute(id, dataType, value);
    return this.communicator.send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConceptresponse().getConcept()))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getAttribute = async function (id, value) {
    const dataTypeTxRequest = TxRequestBuilder.getDataTypeOfType(id);
    const resp = await this.communicator.send(dataTypeTxRequest);
    const dataType = resp.getConceptresponse().getOptionaldatatype().getPresent();
    const txRequest = TxRequestBuilder.getAttribute(id, dataType, value);
    return this.communicator
        .send(txRequest)
        .then((response) => {
            const optionalConcept = response.getConceptresponse().getOptionalconcept();
            if (optionalConcept.hasPresent())
                return this.conceptFactory.createConcept(optionalConcept.getPresent());
            else
                return null;
        })
        .catch((e) => { throw e; });
};
GraknGrpcService.prototype.getDataTypeOfType = function (id) {
    const txRequest = TxRequestBuilder.getDataTypeOfType(id);
    return this.communicator.send(txRequest)
        .then(response => {
            const optionalDatatype = response.getConceptresponse().getOptionaldatatype();
            return (optionalDatatype.hasPresent()) ? _dataTypeToString(optionalDatatype.getPresent()) : null;
        })
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getRegex = function (id) {
    const txRequest = TxRequestBuilder.getRegex(id);
    return this.communicator.send(txRequest)
        .then(response => {
            const optionalRegex = response.getConceptresponse().getOptionalregex();
            return (optionalRegex.hasPresent()) ? optionalRegex.getPresent() : null;
        })
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setRegex = function (id, regex) {
    const txRequest = TxRequestBuilder.setRegex(id, regex);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};


//Thing

GraknGrpcService.prototype.isInferred = function (id) {
    const txRequest = TxRequestBuilder.isInferred(id);
    return this.communicator.send(txRequest)
        .then(resp => resp.getConceptresponse().getBool())
        .catch(e => { throw e; });
}

GraknGrpcService.prototype.getDirectType = function (id) {
    const txRequest = TxRequestBuilder.getDirectType(id);
    return this.communicator.send(txRequest)
        .then(response => {
            const concept = response.getConceptresponse().getConcept();
            return this.conceptFactory.createConcept(concept);
        })
        .catch(e => { throw e; });
};

GraknGrpcService.prototype.getRelationships = function (id) {
    const txRequest = TxRequestBuilder.getRelationships(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
}

GraknGrpcService.prototype.getRelationshipsByRoles = function (id, roles) {
    const txRequest = TxRequestBuilder.getRelationshipsByRoles(id, roles);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};

GraknGrpcService.prototype.getRolesPlayedByThing = function (id) {
    const txRequest = TxRequestBuilder.getRolesPlayedByThing(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
}

GraknGrpcService.prototype.getAttributes = function (id) {
    const txRequest = TxRequestBuilder.getAttributes(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getAttributesByTypes = function (id, types) {
    const txRequest = TxRequestBuilder.getAttributesByTypes(id, types);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getKeys = function (id) {
    const txRequest = TxRequestBuilder.getKeys(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getKeysByTypes = function (id, types) {
    const txRequest = TxRequestBuilder.getKeysByTypes(id, types);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setAttribute = function (id, attribute) {
    const txRequest = TxRequestBuilder.setAttribute(id, attribute);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.unsetAttribute = function (id, attribute) {
    const txRequest = TxRequestBuilder.unsetAttribute(id, attribute);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};

// Relationship

GraknGrpcService.prototype.getRolePlayers = function (id) {
    const txRequest = TxRequestBuilder.getRolePlayers(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeRolePlayerIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getRolePlayersByRoles = function (id, roles) {
    const txRequest = TxRequestBuilder.getRolePlayersByRoles(id, roles);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.setRolePlayer = function (id, role, thing) {
    const txRequest = TxRequestBuilder.setRolePlayer(id, role, thing);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.unsetRolePlayer = function (id, role, thing) {
    const txRequest = TxRequestBuilder.unsetRolePlayer(id, role, thing);
    return this.communicator.send(txRequest)
        .catch(e => { throw e; });
};
// Attribute

function _getAttributeValue(resp) {
    const attrValue = resp.getConceptresponse().getAttributevalue();
    if (attrValue.hasString()) return attrValue.getString();
    if (attrValue.hasBoolean()) return attrValue.getBoolean();
    if (attrValue.hasInteger()) return attrValue.getInteger();
    if (attrValue.hasLong()) return attrValue.getLong();
    if (attrValue.hasFloat()) return attrValue.getFloat();
    if (attrValue.hasDouble()) return attrValue.getDouble();
    if (attrValue.hasDate()) return attrValue.getDate();
}

GraknGrpcService.prototype.getValue = function (id) {
    const txRequest = TxRequestBuilder.getValue(id);
    return this.communicator.send(txRequest)
        .then(response => _getAttributeValue(response))
        .catch(e => { throw e; });
};
GraknGrpcService.prototype.getOwners = function (id) {
    const txRequest = TxRequestBuilder.getOwners(id);
    return this.communicator.send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch(e => { throw e; });
};


function _dataTypeToString(dataType) {
    switch (dataType) {
        case 0: return "String";
        case 1: return "Boolean";
        case 2: return "Integer";
        case 3: return "Long";
        case 4: return "Float";
        case 5: return "Double";
        case 6: return "Date";
    }
}

GraknGrpcService.prototype.getDataTypeOfAttribute = function (id) {
    const txRequest = TxRequestBuilder.getDataTypeOfAttribute(id);
    return this.communicator.send(txRequest)
        .then(response => _dataTypeToString(response.getConceptresponse().getDatatype()))
        .catch(e => { throw e; });
};


// ====== UTILS METHODS =====//


/**
 * This method creates and consumes an iterator (until server returns Done) and build Concept object from
 * every response.
 * 
 * Used both with ConceptResponse and TxResponse, they both carry IteratorId, but nested differently.
 * 
 * @param {*} grpcResponse gRPC response that will contain iteratorId
 * @param {*} graknGrpcService graknGrpcService implementation needed to be injected to new concepts that will be built
 */
async function _consumeConceptIterator(grpcResponse, graknGrpcService) {
    const iteratorId = (grpcResponse.hasConceptresponse()) ? grpcResponse.getConceptresponse().getIteratorid() : grpcResponse.getIteratorid();
    const iterator = new GrpcIterator.GrpcConceptIterator(iteratorId, graknGrpcService.communicator);
    const concepts = [];
    let concept = await iterator.nextResult().catch(e => { throw e; });
    while (concept) {
        concepts.push(graknGrpcService.conceptFactory.createConcept(concept));
        concept = await iterator.nextResult().catch(e => { throw e; });
    }
    return concepts;
}

async function _consumeRolePlayerIterator(grpcConceptResponse, graknGrpcService) {
    const iterator = new GrpcIterator.GrpcRolePlayerIterator(
        grpcConceptResponse.getConceptresponse().getIteratorid(),
        graknGrpcService.communicator
    );
    const rolePlayers = [];
    let grpcRolePlayer = await iterator.nextResult().catch(e => { throw e; });
    while (grpcRolePlayer) {
        rolePlayers.push({
            role: graknGrpcService.conceptFactory.createConcept(grpcRolePlayer.getRole()),
            player: graknGrpcService.conceptFactory.createConcept(grpcRolePlayer.getPlayer())
        });
        grpcRolePlayer = await iterator.nextResult().catch(e => { throw e; });
    }
    return rolePlayers;
}

// ======================= Grakn transaction methods ========================= //


GraknGrpcService.prototype.getConcept = function (conceptId) {
    const txRequest = new messages.TxRequest();
    const conceptIdMessage = new messages.ConceptId();
    conceptIdMessage.setValue(conceptId);
    txRequest.setGetconcept(conceptIdMessage);
    return this.communicator
        .send(txRequest)
        .then((response) => {
            const optionalConcept = response.getOptionalconcept();
            if (optionalConcept.hasPresent())
                return this.conceptFactory.createConcept(optionalConcept.getPresent());
            else
                return null;
        })
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.getSchemaConcept = function (label) {
    const txRequest = new messages.TxRequest();
    const labelMessage = new messages.Label();
    labelMessage.setValue(label);
    txRequest.setGetschemaconcept(labelMessage);
    return this.communicator
        .send(txRequest)
        .then((response) => {
            const optionalConcept = response.getOptionalconcept();
            if (optionalConcept.hasPresent())
                return this.conceptFactory.createConcept(optionalConcept.getPresent());
            else
                return null;
        })
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.putEntityType = function (label) {
    const txRequest = new messages.TxRequest();
    const labelMessage = new messages.Label();
    labelMessage.setValue(label);
    txRequest.setPutentitytype(labelMessage);
    return this.communicator
        .send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConcept()))
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.putRelationshipType = function (label) {
    const txRequest = new messages.TxRequest();
    const labelMessage = new messages.Label();
    labelMessage.setValue(label);
    txRequest.setPutrelationshiptype(labelMessage);
    return this.communicator
        .send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConcept()))
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.putRelationshipType = function (label) {
    const txRequest = new messages.TxRequest();
    const labelMessage = new messages.Label();
    labelMessage.setValue(label);
    txRequest.setPutrelationshiptype(labelMessage);
    return this.communicator
        .send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConcept()))
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.putRole = function (label) {
    const txRequest = new messages.TxRequest();
    const labelMessage = new messages.Label();
    labelMessage.setValue(label);
    txRequest.setPutrole(labelMessage);
    return this.communicator
        .send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConcept()))
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.putAttributeType = function (label, dataType) {
    if (dataType == null) throw new Error('Datatype of AttributeType not specified.');
    const txRequest = new messages.TxRequest();
    const putMessage = new messages.PutAttributeType();
    const labelMessage = new messages.Label();
    labelMessage.setValue(label);
    putMessage.setLabel(labelMessage);
    putMessage.setDatatype(dataType);
    txRequest.setPutattributetype(putMessage);
    return this.communicator
        .send(txRequest)
        .then(response => this.conceptFactory.createConcept(response.getConcept()))
        .catch((e) => { throw e; });
}

GraknGrpcService.prototype.getAttributesByValue = function (value, dataType) {
    if (dataType == null) throw new Error('Datatype of AttributeType not specified.');
    const txRequest = new messages.TxRequest();
    const attributeValue = new messages.AttributeValue();
    switch (dataType) {
        case 0: attributeValue.setString(value); break;
        case 1: attributeValue.setBoolean(value); break;
        case 2: attributeValue.setInteger(value); break;
        case 3: attributeValue.setLong(value); break;
        case 4: attributeValue.setFloat(value); break;
        case 5: attributeValue.setDouble(value); break;
        case 6: attributeValue.setDate(value); break;
        default: throw new Error('DataType of attribute not recognised.');
    }
    txRequest.setGetattributesbyvalue(attributeValue);
    return this.communicator
        .send(txRequest)
        .then(response => _consumeConceptIterator(response, this))
        .catch((e) => { throw e; });
}


// OPEN TRANSACTION

GraknGrpcService.prototype.openTx = function (keyspace, txType, credentials) {
    const openRequest = new messages.Open();
    const txRequest = new messages.TxRequest();
    const messageKeyspace = new messages.Keyspace();
    messageKeyspace.setValue(keyspace);

    openRequest.setKeyspace(messageKeyspace);
    openRequest.setTxtype(txType);
    if (credentials) {
        openRequest.setUsername(credentials.username);
        openRequest.setPassword(credentials.password);
    }
    txRequest.setOpen(openRequest);

    return this.communicator.send(txRequest)
        // Explicitly catch and re-throw exception otherwise it will be swallowed by promises
        .catch((e) => { throw e; });
};

// COMMIT TRANSACTION

GraknGrpcService.prototype.commit = function () {
    const commitRequest = new messages.Commit();
    const txRequest = new messages.TxRequest();
    txRequest.setCommit(commitRequest);
    return this.communicator.send(txRequest).catch((e) => { throw e; });
}


// EXEC QUERY
/**
 * Execute query and always return array of concepts. Returns empty array if server
 * returns Done.
 */

GraknGrpcService.prototype.execute = function executeQuery(query) {
    const txRequest = new messages.TxRequest();
    const executeQuery = new messages.ExecQuery();
    const queryRequest = new messages.Query();
    queryRequest.setValue(query);
    executeQuery.setQuery(queryRequest);
    txRequest.setExecquery(executeQuery);
    return this.communicator
        .send(txRequest)
        .then(resp => this._parseResponse(resp))
        .catch((e) => { throw e; });
};

GraknGrpcService.prototype._parseResponse = async function parseResponse(resp) {
    if (resp.hasDone()) return [];
    if (resp.hasIteratorid()) {
        const iterator = new GrpcIterator.GrpcQueryIterator(
            resp.getIteratorid(),
            this.communicator
        );
        const executeQueryResult = [];
        let nextResult = await iterator.nextResult();
        while (nextResult) {
            executeQueryResult.push(this._parseResult(nextResult));
            nextResult = await iterator.nextResult();
        }
        return executeQueryResult;
    }
    if (resp.hasQueryresult()) {
        return [this._parseResult(resp.getQueryresult())];
    }
};

GraknGrpcService.prototype._parseResult = function parseResult(queryResult) {
    if (queryResult.hasOtherresult()) {
        // compute or aggregate query
        return JSON.parse(queryResult.getOtherresult());
    } else {
        const answerMap = new Map();
        queryResult
            .getAnswer()
            .getAnswerMap()
            .forEach((grpcConcept, key) => {
                answerMap.set(
                    key,
                    this.conceptFactory.createConcept(grpcConcept));
            });
        return answerMap;
    }
};

module.exports = GraknGrpcService;